# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = ["github.com/golang/mock/mockgen/model"]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.27.0"

[[constraint]]
  name = "github.com/cihub/seelog"
  revision = "f561c5e57575bb1e0a2167028b7339b3a8d16fb4"

[[constraint]]
  name = "github.com/containerd/cgroups"
  revision ="c3fc2b77b568af2406f3931cf3d3f17d76736886"

[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "0.7.0"

[[constraint]]
  name = "github.com/deniswernert/udev"
  revision ="82fe5be8ca5f7d8255cc838723687f61bb175120"

[[constraint]]
  name = "github.com/docker/docker"
  branch = "master"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

[[constraint]]
  name = "github.com/golang/mock"
  version ="1.1.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "v1.2.0"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  revision ="d349388c43b01b2ea695965ae561b5bddb81318f"

[[constraint]]
  name = "github.com/pborman/uuid"
  revision ="ca53cad383cad2479bbba7f7a1a05797ec1386e4"

[[constraint]]
  name = "github.com/pkg/errors"
  revision ="c605e284fe17294bda444b34710735b29d1a9d90"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision ="f35b8ab0b5a2cef36673838d662e249dd9c94686"

[[constraint]]
  name = "github.com/vishvananda/netlink"
  revision ="fe3b5664d23a11b52ba59bece4ff29c52772a56b"

[[constraint]]
  name = "github.com/didip/tollbooth"
  version = "3.0.2"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.0"

[[constraint]]
  branch = "master"
  name = "github.com/awslabs/go-config-generator-for-fluentd-and-fluentbit"
