
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.10.30"

[[constraint]]
  name = "github.com/cihub/seelog"

[[constraint]]
  name = "github.com/containerd/cgroups"

[[constraint]]
  name = "github.com/containernetworking/cni"
  version = "0.5.2"

[[constraint]]
  name = "github.com/deniswernert/udev"

[[constraint]]
  name = "github.com/docker/docker"

[[constraint]]
  name = "github.com/fsouza/go-dockerclient"

[[constraint]]
  name = "github.com/golang/mock"

[[constraint]]
  name = "github.com/gorilla/websocket"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"

[[constraint]]
  name = "github.com/pborman/uuid"

[[constraint]]
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "github.com/vishvananda/netlink"

[[constraint]]
  name = "golang.org/x/net"

[[constraint]]
  name = "golang.org/x/sys"

[[constraint]]
  name = "golang.org/x/tools"
